//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SidebarDiagnostics.Framework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SidebarDiagnostics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar Diagnostics.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string ButtonDonate {
            get {
                return ResourceManager.GetString("ButtonDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ButtonDone {
            get {
                return ResourceManager.GetString("ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string ButtonGitHub {
            get {
                return ResourceManager.GetString("ButtonGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string ButtonGraph {
            get {
                return ResourceManager.GetString("ButtonGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string ButtonHide {
            get {
                return ResourceManager.GetString("ButtonHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string ButtonReload {
            get {
                return ResourceManager.GetString("ButtonReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ButtonShow {
            get {
                return ResourceManager.GetString("ButtonShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string ButtonSkip {
            get {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string ButtonVisibility {
            get {
                return ResourceManager.GetString("ButtonVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log.
        /// </summary>
        public static string ChangeLogTitle {
            get {
                return ResourceManager.GetString("ChangeLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string CPUClock {
            get {
                return ResourceManager.GetString("CPUClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string CPUClockLabel {
            get {
                return ResourceManager.GetString("CPUClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Clock.
        /// </summary>
        public static string CPUCoreClock {
            get {
                return ResourceManager.GetString("CPUCoreClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string CPUCoreClockLabel {
            get {
                return ResourceManager.GetString("CPUCoreClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Load.
        /// </summary>
        public static string CPUCoreLoad {
            get {
                return ResourceManager.GetString("CPUCoreLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string CPUCoreLoadLabel {
            get {
                return ResourceManager.GetString("CPUCoreLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Usage.
        /// </summary>
        public static string CPUFan {
            get {
                return ResourceManager.GetString("CPUFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        public static string CPUFanLabel {
            get {
                return ResourceManager.GetString("CPUFanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string CPULoad {
            get {
                return ResourceManager.GetString("CPULoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string CPULoadLabel {
            get {
                return ResourceManager.GetString("CPULoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string CPUTemp {
            get {
                return ResourceManager.GetString("CPUTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string CPUTempLabel {
            get {
                return ResourceManager.GetString("CPUTempLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string CPUVoltage {
            get {
                return ResourceManager.GetString("CPUVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string CPUVoltageLabel {
            get {
                return ResourceManager.GetString("CPUVoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string DriveFree {
            get {
                return ResourceManager.GetString("DriveFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string DriveFreeLabel {
            get {
                return ResourceManager.GetString("DriveFreeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string DriveLoad {
            get {
                return ResourceManager.GetString("DriveLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Bar.
        /// </summary>
        public static string DriveLoadBar {
            get {
                return ResourceManager.GetString("DriveLoadBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string DriveLoadBarLabel {
            get {
                return ResourceManager.GetString("DriveLoadBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string DriveLoadLabel {
            get {
                return ResourceManager.GetString("DriveLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Rate.
        /// </summary>
        public static string DriveRead {
            get {
                return ResourceManager.GetString("DriveRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string DriveReadLabel {
            get {
                return ResourceManager.GetString("DriveReadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        public static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string DriveUsed {
            get {
                return ResourceManager.GetString("DriveUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string DriveUsedLabel {
            get {
                return ResourceManager.GetString("DriveUsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Rate.
        /// </summary>
        public static string DriveWrite {
            get {
                return ResourceManager.GetString("DriveWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string DriveWriteLabel {
            get {
                return ResourceManager.GetString("DriveWriteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Performance Counter cache is corrupted. Click OK to visit the wiki and fix this error..
        /// </summary>
        public static string ErrorPerformanceCounter {
            get {
                return ResourceManager.GetString("ErrorPerformanceCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU.
        /// </summary>
        public static string GPU {
            get {
                return ResourceManager.GetString("GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Clock.
        /// </summary>
        public static string GPUCoreClock {
            get {
                return ResourceManager.GetString("GPUCoreClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string GPUCoreClockLabel {
            get {
                return ResourceManager.GetString("GPUCoreClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Load.
        /// </summary>
        public static string GPUCoreLoad {
            get {
                return ResourceManager.GetString("GPUCoreLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string GPUCoreLoadLabel {
            get {
                return ResourceManager.GetString("GPUCoreLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Usage.
        /// </summary>
        public static string GPUFan {
            get {
                return ResourceManager.GetString("GPUFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        public static string GPUFanLabel {
            get {
                return ResourceManager.GetString("GPUFanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string GPUTemp {
            get {
                return ResourceManager.GetString("GPUTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string GPUTempLabel {
            get {
                return ResourceManager.GetString("GPUTempLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string GPUVoltage {
            get {
                return ResourceManager.GetString("GPUVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string GPUVoltageLabel {
            get {
                return ResourceManager.GetString("GPUVoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM Clock.
        /// </summary>
        public static string GPUVRAMClock {
            get {
                return ResourceManager.GetString("GPUVRAMClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM.
        /// </summary>
        public static string GPUVRAMClockLabel {
            get {
                return ResourceManager.GetString("GPUVRAMClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM Load.
        /// </summary>
        public static string GPUVRAMLoad {
            get {
                return ResourceManager.GetString("GPUVRAMLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM.
        /// </summary>
        public static string GPUVRAMLoadLabel {
            get {
                return ResourceManager.GetString("GPUVRAMLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string GraphConfigSectionTitle {
            get {
                return ResourceManager.GetString("GraphConfigSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string GraphDuration {
            get {
                return ResourceManager.GetString("GraphDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string GraphDurationMinute {
            get {
                return ResourceManager.GetString("GraphDurationMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string GraphDurationMinutes {
            get {
                return ResourceManager.GetString("GraphDurationMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string GraphDurationSeconds {
            get {
                return ResourceManager.GetString("GraphDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        public static string GraphHardware {
            get {
                return ResourceManager.GetString("GraphHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        public static string GraphMetrics {
            get {
                return ResourceManager.GetString("GraphMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string GraphMonitor {
            get {
                return ResourceManager.GetString("GraphMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string GraphTitle {
            get {
                return ResourceManager.GetString("GraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the app..
        /// </summary>
        public static string LanguageChangedText {
            get {
                return ResourceManager.GetString("LanguageChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed.
        /// </summary>
        public static string LanguageChangedTitle {
            get {
                return ResourceManager.GetString("LanguageChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External IP Address.
        /// </summary>
        public static string NetworkExtIP {
            get {
                return ResourceManager.GetString("NetworkExtIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.
        /// </summary>
        public static string NetworkExtIPLabel {
            get {
                return ResourceManager.GetString("NetworkExtIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth In.
        /// </summary>
        public static string NetworkIn {
            get {
                return ResourceManager.GetString("NetworkIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string NetworkInLabel {
            get {
                return ResourceManager.GetString("NetworkInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string NetworkIP {
            get {
                return ResourceManager.GetString("NetworkIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string NetworkIPLabel {
            get {
                return ResourceManager.GetString("NetworkIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth Out.
        /// </summary>
        public static string NetworkOut {
            get {
                return ResourceManager.GetString("NetworkOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string NetworkOutLabel {
            get {
                return ResourceManager.GetString("NetworkOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        public static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string RAMClock {
            get {
                return ResourceManager.GetString("RAMClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string RAMClockLabel {
            get {
                return ResourceManager.GetString("RAMClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string RAMFree {
            get {
                return ResourceManager.GetString("RAMFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string RAMFreeLabel {
            get {
                return ResourceManager.GetString("RAMFreeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string RAMLoad {
            get {
                return ResourceManager.GetString("RAMLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string RAMLoadLabel {
            get {
                return ResourceManager.GetString("RAMLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string RAMUsed {
            get {
                return ResourceManager.GetString("RAMUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string RAMUsedLabel {
            get {
                return ResourceManager.GetString("RAMUsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string RAMVoltage {
            get {
                return ResourceManager.GetString("RAMVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string RAMVoltageLabel {
            get {
                return ResourceManager.GetString("RAMVoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 Hour Clock.
        /// </summary>
        public static string Settings24HourClock {
            get {
                return ResourceManager.GetString("Settings24HourClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the clock&apos;s time format to 24 hours..
        /// </summary>
        public static string Settings24HourClockTooltip {
            get {
                return ResourceManager.GetString("Settings24HourClockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string SettingsAdvancedTab {
            get {
                return ResourceManager.GetString("SettingsAdvancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Blink.
        /// </summary>
        public static string SettingsAlertBlink {
            get {
                return ResourceManager.GetString("SettingsAlertBlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes the alert text blink..
        /// </summary>
        public static string SettingsAlertBlinkTooltip {
            get {
                return ResourceManager.GetString("SettingsAlertBlinkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Font Color.
        /// </summary>
        public static string SettingsAlertFontColor {
            get {
                return ResourceManager.GetString("SettingsAlertFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of alert text..
        /// </summary>
        public static string SettingsAlertFontColorTooltip {
            get {
                return ResourceManager.GetString("SettingsAlertFontColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Core Clocks.
        /// </summary>
        public static string SettingsAllCoreClocks {
            get {
                return ResourceManager.GetString("SettingsAllCoreClocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the clock speeds of all cores not just the first..
        /// </summary>
        public static string SettingsAllCoreClocksTooltip {
            get {
                return ResourceManager.GetString("SettingsAllCoreClocksTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On Top.
        /// </summary>
        public static string SettingsAlwaysOnTop {
            get {
                return ResourceManager.GetString("SettingsAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes the sidebar always on top of other windows..
        /// </summary>
        public static string SettingsAlwaysOnTopTooltip {
            get {
                return ResourceManager.GetString("SettingsAlwaysOnTopTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Background Color.
        /// </summary>
        public static string SettingsAutoBackground {
            get {
                return ResourceManager.GetString("SettingsAutoBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the background color to your Windows color settings..
        /// </summary>
        public static string SettingsAutoBackgroundTooltip {
            get {
                return ResourceManager.GetString("SettingsAutoBackgroundTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update.
        /// </summary>
        public static string SettingsAutoUpdate {
            get {
                return ResourceManager.GetString("SettingsAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates the app automatically..
        /// </summary>
        public static string SettingsAutoUpdateTooltip {
            get {
                return ResourceManager.GetString("SettingsAutoUpdateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string SettingsBackgroundColor {
            get {
                return ResourceManager.GetString("SettingsBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of the background..
        /// </summary>
        public static string SettingsBackgroundColorTooltip {
            get {
                return ResourceManager.GetString("SettingsBackgroundColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Opacity.
        /// </summary>
        public static string SettingsBackgroundOpacity {
            get {
                return ResourceManager.GetString("SettingsBackgroundOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity of the background..
        /// </summary>
        public static string SettingsBackgroundOpacityTooltip {
            get {
                return ResourceManager.GetString("SettingsBackgroundOpacityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth In Alert.
        /// </summary>
        public static string SettingsBandwidthInAlert {
            get {
                return ResourceManager.GetString("SettingsBandwidthInAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kbps or kBps threshold at which bandwidth received alerts occur. Use 0 to disable..
        /// </summary>
        public static string SettingsBandwidthInAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsBandwidthInAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth Out Alert.
        /// </summary>
        public static string SettingsBandwidthOutAlert {
            get {
                return ResourceManager.GetString("SettingsBandwidthOutAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kbps or kBps threshold at which bandwidth sent alerts occur. Use 0 to disable..
        /// </summary>
        public static string SettingsBandwidthOutAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsBandwidthOutAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Through.
        /// </summary>
        public static string SettingsClickThrough {
            get {
                return ResourceManager.GetString("SettingsClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes mouse events pass through the window. Note this will prevent any interaction with the sidebar..
        /// </summary>
        public static string SettingsClickThroughTooltip {
            get {
                return ResourceManager.GetString("SettingsClickThroughTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Menu Bar.
        /// </summary>
        public static string SettingsCollapseMenuBar {
            get {
                return ResourceManager.GetString("SettingsCollapseMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the extra space at the top of the sidebar..
        /// </summary>
        public static string SettingsCollapseMenuBarTooltip {
            get {
                return ResourceManager.GetString("SettingsCollapseMenuBarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Core Loads.
        /// </summary>
        public static string SettingsCoreLoads {
            get {
                return ResourceManager.GetString("SettingsCoreLoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the percentage load of all cores..
        /// </summary>
        public static string SettingsCoreLoadsTooltip {
            get {
                return ResourceManager.GetString("SettingsCoreLoadsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string SettingsCustomizeTab {
            get {
                return ResourceManager.GetString("SettingsCustomizeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        public static string SettingsDateFormat {
            get {
                return ResourceManager.GetString("SettingsDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string SettingsDateFormatDisabled {
            get {
                return ResourceManager.GetString("SettingsDateFormatDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of the date below the clock..
        /// </summary>
        public static string SettingsDateFormatTooltip {
            get {
                return ResourceManager.GetString("SettingsDateFormatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string SettingsDock {
            get {
                return ResourceManager.GetString("SettingsDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string SettingsDockBottom {
            get {
                return ResourceManager.GetString("SettingsDockBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string SettingsDockLeft {
            get {
                return ResourceManager.GetString("SettingsDockLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string SettingsDockRight {
            get {
                return ResourceManager.GetString("SettingsDockRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which edge the sidebar will dock to..
        /// </summary>
        public static string SettingsDockTooltip {
            get {
                return ResourceManager.GetString("SettingsDockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string SettingsDockTop {
            get {
                return ResourceManager.GetString("SettingsDockTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows extra drive details as text..
        /// </summary>
        public static string SettingsDriveDetailsTooltip {
            get {
                return ResourceManager.GetString("SettingsDriveDetailsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        public static string SettingsFontColor {
            get {
                return ResourceManager.GetString("SettingsFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of text and icons..
        /// </summary>
        public static string SettingsFontColorTooltip {
            get {
                return ResourceManager.GetString("SettingsFontColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string SettingsFontSize {
            get {
                return ResourceManager.GetString("SettingsFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of text and icons..
        /// </summary>
        public static string SettingsFontSizeTooltip {
            get {
                return ResourceManager.GetString("SettingsFontSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsGeneralTab {
            get {
                return ResourceManager.GetString("SettingsGeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string SettingsHardwareColumn1 {
            get {
                return ResourceManager.GetString("SettingsHardwareColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        public static string SettingsHardwareColumn2 {
            get {
                return ResourceManager.GetString("SettingsHardwareColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables this hardware..
        /// </summary>
        public static string SettingsHardwareEnabledTooltip {
            get {
                return ResourceManager.GetString("SettingsHardwareEnabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the name of this hardware..
        /// </summary>
        public static string SettingsHardwareNameTooltip {
            get {
                return ResourceManager.GetString("SettingsHardwareNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Offset.
        /// </summary>
        public static string SettingsHorizontalOffset {
            get {
                return ResourceManager.GetString("SettingsHorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal offset of the sidebar..
        /// </summary>
        public static string SettingsHorizontalOffsetTooltip {
            get {
                return ResourceManager.GetString("SettingsHorizontalOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SettingsHotkeyClose {
            get {
                return ResourceManager.GetString("SettingsHotkeyClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Edge.
        /// </summary>
        public static string SettingsHotkeyCycleEdge {
            get {
                return ResourceManager.GetString("SettingsHotkeyCycleEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Screen.
        /// </summary>
        public static string SettingsHotkeyCycleScreen {
            get {
                return ResourceManager.GetString("SettingsHotkeyCycleScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string SettingsHotkeyHide {
            get {
                return ResourceManager.GetString("SettingsHotkeyHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string SettingsHotkeyReload {
            get {
                return ResourceManager.GetString("SettingsHotkeyReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Space.
        /// </summary>
        public static string SettingsHotkeyReserveSpace {
            get {
                return ResourceManager.GetString("SettingsHotkeyReserveSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string SettingsHotkeyShow {
            get {
                return ResourceManager.GetString("SettingsHotkeyShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string SettingsHotkeysTab {
            get {
                return ResourceManager.GetString("SettingsHotkeysTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        public static string SettingsHotkeyToggle {
            get {
                return ResourceManager.GetString("SettingsHotkeyToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide at Startup.
        /// </summary>
        public static string SettingsInitiallyHidden {
            get {
                return ResourceManager.GetString("SettingsInitiallyHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes the sidebar hide at startup..
        /// </summary>
        public static string SettingsInitiallyHiddenTooltip {
            get {
                return ResourceManager.GetString("SettingsInitiallyHiddenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsLanguageDefault {
            get {
                return ResourceManager.GetString("SettingsLanguageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language of the app..
        /// </summary>
        public static string SettingsLanguageTooltip {
            get {
                return ResourceManager.GetString("SettingsLanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics:.
        /// </summary>
        public static string SettingsMetrics {
            get {
                return ResourceManager.GetString("SettingsMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable specific metrics..
        /// </summary>
        public static string SettingsMetricsTooltip {
            get {
                return ResourceManager.GetString("SettingsMetricsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables this monitor..
        /// </summary>
        public static string SettingsMonitorEnabledTooltip {
            get {
                return ResourceManager.GetString("SettingsMonitorEnabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string SettingsMonitorsColumn1 {
            get {
                return ResourceManager.GetString("SettingsMonitorsColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string SettingsMonitorsColumn2 {
            get {
                return ResourceManager.GetString("SettingsMonitorsColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click a row to edit its settings..
        /// </summary>
        public static string SettingsMonitorsSubtitle1 {
            get {
                return ResourceManager.GetString("SettingsMonitorsSubtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a row to change its order..
        /// </summary>
        public static string SettingsMonitorsSubtitle2 {
            get {
                return ResourceManager.GetString("SettingsMonitorsSubtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors.
        /// </summary>
        public static string SettingsMonitorsTab {
            get {
                return ResourceManager.GetString("SettingsMonitorsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling Interval.
        /// </summary>
        public static string SettingsPollingInterval {
            get {
                return ResourceManager.GetString("SettingsPollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time between polling for data in milliseconds..
        /// </summary>
        public static string SettingsPollingIntervalTooltip {
            get {
                return ResourceManager.GetString("SettingsPollingIntervalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Space.
        /// </summary>
        public static string SettingsReserveSpace {
            get {
                return ResourceManager.GetString("SettingsReserveSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserves space in the work area for the sidebar..
        /// </summary>
        public static string SettingsReserveSpaceTooltip {
            get {
                return ResourceManager.GetString("SettingsReserveSpaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round All Decimals.
        /// </summary>
        public static string SettingsRoundAllDecimals {
            get {
                return ResourceManager.GetString("SettingsRoundAllDecimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round all decimal values to the nearest integer..
        /// </summary>
        public static string SettingsRoundAllDecimalsTooltip {
            get {
                return ResourceManager.GetString("SettingsRoundAllDecimalsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at Startup.
        /// </summary>
        public static string SettingsRunAtStartup {
            get {
                return ResourceManager.GetString("SettingsRunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs the app when you first log in..
        /// </summary>
        public static string SettingsRunAtStartupTooltip {
            get {
                return ResourceManager.GetString("SettingsRunAtStartupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        public static string SettingsScreen {
            get {
                return ResourceManager.GetString("SettingsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which screen the sidebar will be on..
        /// </summary>
        public static string SettingsScreenTooltip {
            get {
                return ResourceManager.GetString("SettingsScreenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Clock.
        /// </summary>
        public static string SettingsShowClock {
            get {
                return ResourceManager.GetString("SettingsShowClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the clock..
        /// </summary>
        public static string SettingsShowClockTooltip {
            get {
                return ResourceManager.GetString("SettingsShowClockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Drive Details.
        /// </summary>
        public static string SettingsShowDriveDetails {
            get {
                return ResourceManager.GetString("SettingsShowDriveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Drive IO.
        /// </summary>
        public static string SettingsShowDriveIO {
            get {
                return ResourceManager.GetString("SettingsShowDriveIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows drive read and write speeds if drive details is enabled..
        /// </summary>
        public static string SettingsShowDriveIOTooltip {
            get {
                return ResourceManager.GetString("SettingsShowDriveIOTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Drive Space.
        /// </summary>
        public static string SettingsShowDriveSpace {
            get {
                return ResourceManager.GetString("SettingsShowDriveSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows load percent, used space, and free space if drive details is enabled..
        /// </summary>
        public static string SettingsShowDriveSpaceTooltip {
            get {
                return ResourceManager.GetString("SettingsShowDriveSpaceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hardware Names.
        /// </summary>
        public static string SettingsShowHardwareNames {
            get {
                return ResourceManager.GetString("SettingsShowHardwareNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows hardware names..
        /// </summary>
        public static string SettingsShowHardwareNamesTooltip {
            get {
                return ResourceManager.GetString("SettingsShowHardwareNamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tray Icon.
        /// </summary>
        public static string SettingsShowTrayIcon {
            get {
                return ResourceManager.GetString("SettingsShowTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the tray icon in the taskbar. This is sometimes required..
        /// </summary>
        public static string SettingsShowTrayIconTooltip {
            get {
                return ResourceManager.GetString("SettingsShowTrayIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar Width.
        /// </summary>
        public static string SettingsSidebarWidth {
            get {
                return ResourceManager.GetString("SettingsSidebarWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of the sidebar in pixels..
        /// </summary>
        public static string SettingsSidebarWidthTooltip {
            get {
                return ResourceManager.GetString("SettingsSidebarWidthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Alert.
        /// </summary>
        public static string SettingsTemperatureAlert {
            get {
                return ResourceManager.GetString("SettingsTemperatureAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temperature threshold at which alerts occur. Use 0 to disable..
        /// </summary>
        public static string SettingsTemperatureAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsTemperatureAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Align.
        /// </summary>
        public static string SettingsTextAlign {
            get {
                return ResourceManager.GetString("SettingsTextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string SettingsTextAlignLeft {
            get {
                return ResourceManager.GetString("SettingsTextAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string SettingsTextAlignRight {
            get {
                return ResourceManager.GetString("SettingsTextAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment of metric text..
        /// </summary>
        public static string SettingsTextAlignTooltip {
            get {
                return ResourceManager.GetString("SettingsTextAlignTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar Mode.
        /// </summary>
        public static string SettingsToolbarMode {
            get {
                return ResourceManager.GetString("SettingsToolbarMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides the sidebar in alt-tab and makes it persist between virtual desktops..
        /// </summary>
        public static string SettingsToolbarModeTooltip {
            get {
                return ResourceManager.GetString("SettingsToolbarModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Scale.
        /// </summary>
        public static string SettingsUIScale {
            get {
                return ResourceManager.GetString("SettingsUIScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale of all windows and UI components..
        /// </summary>
        public static string SettingsUIScaleTooltip {
            get {
                return ResourceManager.GetString("SettingsUIScaleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Bytes Per Second.
        /// </summary>
        public static string SettingsUseBytesPerSecond {
            get {
                return ResourceManager.GetString("SettingsUseBytesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows bandwidth in bytes instead of bits per second..
        /// </summary>
        public static string SettingsUseBytesPerSecondTooltip {
            get {
                return ResourceManager.GetString("SettingsUseBytesPerSecondTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Space Alert.
        /// </summary>
        public static string SettingsUsedSpaceAlert {
            get {
                return ResourceManager.GetString("SettingsUsedSpaceAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage threshold at which used space alerts occur. Use 0 to disable..
        /// </summary>
        public static string SettingsUsedSpaceAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsUsedSpaceAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Fahrenheit.
        /// </summary>
        public static string SettingsUseFahrenheit {
            get {
                return ResourceManager.GetString("SettingsUseFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatures for sensors and alerts will be in Fahrenheit instead of Celcius..
        /// </summary>
        public static string SettingsUseFahrenheitTooltip {
            get {
                return ResourceManager.GetString("SettingsUseFahrenheitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use GHz.
        /// </summary>
        public static string SettingsUseGHz {
            get {
                return ResourceManager.GetString("SettingsUseGHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock speeds will be in GHz instead of MHz..
        /// </summary>
        public static string SettingsUseGHzTooltip {
            get {
                return ResourceManager.GetString("SettingsUseGHzTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Offset.
        /// </summary>
        public static string SettingsVerticalOffset {
            get {
                return ResourceManager.GetString("SettingsVerticalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical offset of the sidebar..
        /// </summary>
        public static string SettingsVerticalOffsetTooltip {
            get {
                return ResourceManager.GetString("SettingsVerticalOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Desktop.
        /// </summary>
        public static string SettingsVirtualDesktop {
            get {
                return ResourceManager.GetString("SettingsVirtualDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables support for virtual desktops..
        /// </summary>
        public static string SettingsVirtualDesktopTooltip {
            get {
                return ResourceManager.GetString("SettingsVirtualDesktopTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the sliders and textboxes to move the sidebar to the correct position..
        /// </summary>
        public static string SetupCustomSubtitle {
            get {
                return ResourceManager.GetString("SetupCustomSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string SetupCustomTitle {
            get {
                return ResourceManager.GetString("SetupCustomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to customize the sidebar click the settings button..
        /// </summary>
        public static string SetupDoneSubtitle {
            get {
                return ResourceManager.GetString("SetupDoneSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also access the settings via the gear icon at the top-right of the sidebar or via the tray icon in the taskbar..
        /// </summary>
        public static string SetupDoneText {
            get {
                return ResourceManager.GetString("SetupDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string SetupDoneTitle {
            get {
                return ResourceManager.GetString("SetupDoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a quick setup to get the sidebar in the correct position..
        /// </summary>
        public static string SetupSubtitle {
            get {
                return ResourceManager.GetString("SetupSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the sidebar visible and docked to the right edge of your primary monitor?.
        /// </summary>
        public static string SetupText {
            get {
                return ResourceManager.GetString("SetupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Setup.
        /// </summary>
        public static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar.
        /// </summary>
        public static string Sidebar {
            get {
                return ResourceManager.GetString("Sidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occurred while trying to update. Auto update is now disabled..
        /// </summary>
        public static string UpdateErrorFatalText {
            get {
                return ResourceManager.GetString("UpdateErrorFatalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update. Check your internet connection..
        /// </summary>
        public static string UpdateErrorText {
            get {
                return ResourceManager.GetString("UpdateErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Error.
        /// </summary>
        public static string UpdateErrorTitle {
            get {
                return ResourceManager.GetString("UpdateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version..
        /// </summary>
        public static string UpdateSuccessText {
            get {
                return ResourceManager.GetString("UpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
    }
}
